apiVersion: v1
kind: PersistentVolume
metadata:
  name: ytdl-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: library.gustend.local
    path: /volume1/Media/Youtube
  storageClassName: nfs-ytdl-downloads
