
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-ytdl-downloads

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi
