apiVersion: v1
kind: Service
metadata:
  name: ytdl
  labels:
    app.kubernetes.io/name: ytdl
spec:
  type: ClusterIP
  ports:
    - port: 8945
      targetPort: 8945
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ytdl
