ghostUsername: gustin
ghostBlogTitle: Gustend
ghostHost: blog.gustend.net
ingress:
  enabled: true
  hostname: "blog.gustend.net"
  ingressClassName: "external"

livenessProbe:
  initialDelaySeconds: 360
readinessProbe:
  initialDelaySeconds: 360