ghostUsername: gustin
ghostBlogTitle: Gustend
ghostHost: blog.gustend.net
ingress:
  enabled: true
  hostname: blog.gustend.net
  ingressClassName: "external"


livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1