apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  labels:
    app.kubernetes.io/name: jellyseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyseer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyseer
    spec:
      containers:
        - name: jellyseer
          image: fallenbagel/jellyseerr:2.7.3
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "America/Chicago"
            - name: PORT
              value: "5055"
          ports:
            - containerPort: 5055
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /app/config
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseer-config
