apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi
