apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secret-store
  kind: ClusterSecretStore
  target:
    name: discord-token
    creationPolicy: Owner
  data:
    - secretKey: discord-token
      remoteRef:
        key: discord-token
