apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-sa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore
  target:
    name: google-sa
    creationPolicy: Owner
  data:
    - secretKey: client_secret.json
      remoteRef:
        key: google-sa
