apiVersion: apps/v1
kind: Deployment
metadata:
  name: ersatztv
  labels:
    app.kubernetes.io/name: ersatztv
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ersatztv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ersatztv
    spec:
      containers:
        - name: ersatztv
          image: ghcr.io/ersatztv/ersatztv:latest
          ports:
            - containerPort: 8409
          env:
            - name: TZ
              value: "America/Chicago"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ersatztv-config
        - name: transcode
          emptyDir:
            medium: Memory
