apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app.kubernetes.io/name: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: init-perms
          image: alpine:3.22
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eux
              # Best-effort perms on local/iSCSI config volume
              chmod -R 775 /config || true
              chown -R 1000:1000 /config || true
              # NOTE: /downloads is NFS (root_squash). Skipping chown/chmod to avoid
              # noisy "Operation not permitted" errors. Ensure NAS path ownership
              # is set to uid:gid 1000:1000, or adjust NFS export mapping on the NAS.
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      containers:
        - name: nzbget
          image: linuxserver/nzbget:v25.3-ls214
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "UTC"
          ports:
            - containerPort: 6789
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: nzbget-downloads-pvc
