---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-library-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-library-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
      storage: 2Ti
  storageClassName: nfs-library-media
