---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      pv-role: tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sonarr-nfs-library-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      pv-role: downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sonarr-nfs-library-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      pv-role: media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: sonarr-nfs-library-media
