gitops:
  repo: https://github.com/mwgustin/homeops
  revision: main

# List of application corresponding to different sync waves
apps:
  - name: ingress-nginx-internal
    namespace: ingress-nginx-internal
    path: cluster/apps/ingress-nginx-internal
    
  - name: ingress-nginx
    namespace: ingress-nginx
    path: cluster/apps/ingress-nginx
    
  - name: metallb
    namespace: metallb-system
    path: cluster/apps/metallb

  - name: cert-manager
    namespace: cert-manager
    path: cluster/apps/cert-manager

  # - name: prometheus
  #   namespace: prometheus
  #   path: cluster/apps/prometheus

  - name: cloudflared
    namespace: default
    path: cluster/apps/cloudflared
  
  - name: test-app
    namespace: default
    path: cluster/apps/test-app
    
  - name: bp-tools
    namespace: default
    path: cluster/apps/bp-tools

  - name: n8n
    namespace: n8n
    path: cluster/apps/n8n

  - name: n8n-ingress
    namespace: n8n
    path: cluster/apps/n8n-ingress

  - name: homepage
    namespace: homepage
    path: cluster/apps/homepage
    
  - name: csi-driver-smb
    namespace: kube-system 
    path: cluster/apps/csi-driver-smb
  - name: csi-driver-nfs
    namespace: kube-system 
    path: cluster/apps/csi-driver-nfs
  - name: metrics-server
    namespace: kube-system
    path: cluster/apps/metrics-server
  - name: external-secrets
    namespace: external-secrets
    path: cluster/apps/external-secrets
  - name: azkv-secret-store
    namespace: external-secrets
    path: cluster/apps/azkv-secret-store
    
  - name: jellyfin
    namespace: media
    path: cluster/apps/jellyfin
  
  - name: discord-activity-bot
    namespace: default
    path: cluster/apps/discord-activity-bot

  - name: postgres-operator
    namespace: postgres-operator
    path: cluster/apps/postgres-operator
  - name: postgres-operator-ui
    namespace: postgres-operator
    path: cluster/apps/postgres-operator-ui
  - name: postgres-operator-ui-ingress
    namespace: postgres-operator
    path: cluster/apps/postgres-operator-ui-ingress

  - name: gustend-ghost
    namespace: ghost-k8s
    path: cluster/apps/ghost

  # - name: ghost-blog
  #   namespace: ghost-k8s
  #   path: cluster/apps/ghost
    
  # - name: ghost2-blog
  #   namespace: ghost2-k8s
  #   path: cluster/apps/ghost2

# repoapps:
#   - name: external-snapshotter-crds
#     namespace: rook-ceph
#     path: client/config/crd
#     repo: https://github.com/kubernetes-csi/external-snapshotter.git
#     revision: master
#     syncWave: 1

  # - name: external-snapshotter-controller
  #   namespace: rook-ceph
  #   path: deploy/kubernetes/snapshot-controller
  #   repo: https://github.com/kubernetes-csi/external-snapshotter.git
  #   revision: master
  #   syncWave: 1

#   - name: external-snapshotter-csi
#     namespace: rook-ceph
#     path: deploy/kubernetes/csi-snapshotter
#     repo: https://github.com/kubernetes-csi/external-snapshotter.git
#     revision: master
#     syncWave: 1

    
    # CDRs App
  # - name: crds
  #   namespace: default
  #   path: cluster/bootstrap/crds
  #   ignoreDifferences:
  #     - group: "*"
  #       kind: "*"
  #       managedFieldsManagers:
  #         - external-secrets
  #   syncWave: 0
  #   # External Secrets Operator
  # - name: external-secrets
  #   namespace: external-secrets
  #   path: argocd/system/external-secrets
  #   syncWave: 1
    # Metal LB
  # - name: metallb
  #   namespace: metallb
  #   path: argocd/system/metallb
  #   syncWave: 2
    # K3S system-upgrade
  # - name: system-upgrade
  #   namespace: system-ugrade
  #   path: argocd/system/system-upgrade
  #   syncWave: 3
    # Cert-Manager and Trust Manager
  # - name: cert-manager
  #   namespace: cert-manager
  #   path: cluster/apps/cert-manager
  #   syncWave: 4
  #   # Linkerd service mesh
  # - name: linkerd
  #   namespace: linkerd
  #   path: argocd/system/linkerd
  #   syncWave: 5
  #   # Traefik Ingress Controller
  # - name: traefik
  #   namespace: traefik
  #   path: argocd/system/traefik
  #   syncWave: 6
  #   helm:
  #     # skip installation traefik CDRs
  #     skipCrds: true
  # - name: nginx
  #   namespace: nginx
  #   path: argocd/system/nginx
  #   syncWave: 6
  #   # CSI External Snapshotter
  # - name: csi-external-snapshotter
  #   namespace: kube-system
  #   path: argocd/system/csi-external-snapshotter
  #   syncWave: 7
  #   # Longhorn Distributed Block Storage
  # - name: longhorn
  #   namespace: longhorn-system
  #   path: argocd/system/longhorn-system
  #   syncWave: 8
  # - name: keycloak
  #   namespace: keycloak
  #   path: argocd/system/keycloak
  #   syncWave: 9
  # - name: oauth2-proxy
  #   namespace: oauth2-proxy
  #   path: argocd/system/oauth2-proxy
  #   syncWave: 10
  #   # Minio Object Storage
  # - name: minio
  #   namespace: minio
  #   path: argocd/system/minio
  #   syncWave: 11
  #   # Velero Backup
  # - name: velero
  #   namespace: velero
  #   path: argocd/system/velero
  #   syncWave: 12
  #   # Logging: Loki and EFK stack
  # - name: logging
  #   namespace: logging
  #   path: argocd/system/logging
  #   syncWave: 13
  #   # Kube-prometheus-stack
  # - name: monitoring
  #   namespace: monitoring
  #   path: argocd/system/monitoring
  #   syncWave: 14
  #   helm:
  #     # skip installation kube-prometheus-stack CDRs
  #     skipCrds: true
  #   # Linkerd-viz
  # - name: linkerd-viz
  #   namespace: linkerd-viz
  #   path: argocd/system/linkerd-viz
  #   syncWave: 15
  #   # Tracing: Tempo
  # - name: tracing
  #   namespace: tracing
  #   path: argocd/system/tracing
  #   syncWave: 16
  #   # Linkerd-jaeger
  # - name: linkerd-jaeger
  #   namespace: linkerd-jaeger
  #   path: argocd/system/linkerd-jaeger
  #   syncWave: 17
  #   # Argo CD App
  # - name: argocd
  #   namespace: argocd
  #   path: argocd/bootstrap/argocd
  #   syncWave: 18
  #   # Kafka App
  # - name: kafka
  #   namespace: kafka
  #   path: argocd/system/kafka
  #   syncWave: 19