apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
    creationPolicy: Owner
  data:
  - secretKey: credentials.json
    remoteRef:
      key: cloudflare-tunnel-credentials