apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/mwgustin
  services.yaml: |
    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - argocd:
        
  docker.yaml: ""


  # widget:
  # type: argocd
  # url: http://argocd.host.or.ip:port
  # key: argocdapikey

  # - kubernetes:
  #   cluster:
  #     # Shows cluster-wide statistics
  #     show: true
  #     # Shows the aggregate CPU stats
  #     cpu: true
  #     # Shows the aggregate memory stats
  #     memory: true
  #     # Shows a custom label
  #     showLabel: true
  #     label: "cluster"
  #   nodes:
  #     # Shows node-specific statistics
  #     show: true
  #     # Shows the CPU for each node
  #     cpu: true
  #     # Shows the memory for each node
  #     memory: true
  #     # Shows the label, which is always the node name
  #     showLabel: true