# helm install ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: nginx-external
    controller:
      replicaCount: 2
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: gustend.net
      ingressClassResource:
        name: external
        default: false
        controllerValue: k8s.io/external
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values: ["external"]
      allowSnippetAnnotations: true