apiVersion: v1
kind: PersistentVolume
metadata:
  name: komga-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: library.gustend.local
    path: /volume1/Media
  storageClassName: komga-nfs-library-media
