apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: komga-nfs-library-media
