apiVersion: v1
kind: Service
metadata:
  name: deluge-service
spec:
  ports:
    - protocol: TCP
      port: 8112 # The service port can be anything, but matching is clear.
      targetPort: 8112 # This must match the port in the Endpoints object.