apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  labels:
    app.kubernetes.io/name: n8n
spec:
  storageClassName: synology-iscsi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
