main:
  config:
    n8n:
      hide_usage_page: true
  secret:
    n8n:
      encryption_key: "my-test-encryption-key"
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  service:
    type: ClusterIP
    port: 80
  persistence:
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    enabled: true
    # what type volume, possible options are [existing, emptyDir, dynamic] dynamic for Dynamic Volume Provisioning, existing for using an existing Claim
    type: dynamic
    # Persistent Volume Storage Class
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.  (gp2 on AWS, standard on
    #   GKE, AWS & OpenStack)
    #
    storageClass: "synology-iscsi"
    # PVC annotations
    #
    # If you need this annotation include it under `values.yml` file and pvc.yml template will add it.
    # This is not maintained at Helm v3 anymore.
    # https://github.com/8gears/n8n-helm-chart/issues/8
    #
    # annotations:
    #   helm.sh/resource-policy: keep
    # Persistent Volume Access Mode
    #
    accessModes:
      - ReadWriteOnce
    # Persistent Volume size
    size: 1Gi
    # Use an existing PVC
    # existingClaim:

# ingress:
#   enabled: true
#   className: "internal"
#   annotations: 
#     - cert-manager.io/cluster-issuer: letsencrypt-prod
#   # define a custom ingress class Name, like "traefik" or "nginx"
#   hosts:
#     - host: n8n.internal.gustend.net
#       paths: ["/"]
#   tls:
#     - secretName: n8n-internal-gustend-net-cert
#       hosts:
#         - n8n.internal.gustend.net
