apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: library.gustend.local
    path: /volume1/Media/docker/deluge-dl
  storageClassName: nfs-deluge-downloads
