apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-k8s-static-ghost
  namespace: ghost-k8s
  labels:
    app: ghost-k8s
    app.kubernetes.io/name: ghost-k8s
    app.kubernetes.io/instance: ghost-k8s
    app.kubernetes.io/version: "5.8"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ghost-k8s
spec:
  storageClassName: synology-iscsi # Change this to your storageClassName
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany # Change this to your accessModes if needed
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ghost-k8s
  namespace: ghost-k8s
  labels:
    app: mysql-ghost-k8s
    app.kubernetes.io/name: mysql-ghost-k8s
    app.kubernetes.io/instance: ghost-k8s
    app.kubernetes.io/version: "5.8"
    app.kubernetes.io/component: database-storage
    app.kubernetes.io/part-of: ghost-k8s

spec:
  storageClassName: synology-iscsi # Change this to your storageClassName
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany # Change this to ReadWriteOnce if you are not using a distributed storage system
  resources:
    requests:
      storage: 2Gi
