apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-k8s-ingress
  namespace: ghost-k8s
spec:
  ingressClassName: external # Or your ingress controller 
  rules:
  - host: blog.gustend.net
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-ghost-k8s
            port:
              name: ghk3s
  # Optional:
  # - host: www.tests.yourdomain.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: ImplementationSpecific
  #       backend:
  #         service:
  #           name: service-ghost-k8s
  #           port:
  #             name: ghk3s


