apiVersion: v1
kind: Service
metadata:
  name: radarr-service
spec:
  ports:
    - protocol: TCP
      port: 7878 # The service port can be anything, but matching is clear.
      targetPort: 7878 # This must match the port in the Endpoints object.