apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kutt-jwt-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore
  target:
    name: kutt-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: kutt-jwt-secret
