apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kutt-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kutt-custom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi
