apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-music-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: library.gustend.local
    path: /volume1/Media/Music
  storageClassName: nfs-library-music
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lidarr-downloads-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: library.gustend.local
    path: /volume1/Media/docker/downloads
  storageClassName: nfs-library-downloads
