apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-music-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-library-music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-library-downloads
