apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
  labels:
    app.kubernetes.io/name: foundry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foundry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundry
    spec:
      containers:
        - name: foundry
          image: felddy/foundryvtt:13.348.0
          ports:
            - containerPort: 30000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: foundry-data
              mountPath: /data
          env:
            - name: FOUNDRY_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: foundry-external-secret
                  key: foundry-admin-key
            - name: FOUNDRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: foundry-external-secret
                  key: foundry-user-name
            - name: FOUNDRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foundry-external-secret
                  key: foundry-user-password
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            claimName: foundry-config-pvc
