apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi