apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-foundry-resources
provisioner: nfs.csi.k8s.io
parameters:
  share: /volume1/Media/docker/foundry/resources
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-foundry-zip
provisioner: nfs.csi.k8s.io
parameters:
  share: /volume1/Media/docker/foundry/zip
